### ISSUE TITLE
how to run in google colab?

### ISSUE THREAD

**Issue by lazezo2** [xtekky/TikTok-Shape-Sec#2]
Can you please explain what that do?, and how to run it in google colab.
i guess it's to sign url and generate tt parameter and cookies, but not sure....
can u please tell me how to get tiktok api to work?, i can use the browser to get the fetch data for example of user feed and make it work through python by sending the same fetch data, but work only if i get fetch data when logged in to tiktok, as u can guess i get panned from tiktok and using browser not load more user video while in private window with no login he can load more user video
any idea?

**Comment by xtekky** [comment]
hi, please consider running it on a proper ide or through terminal on your pc

**Comment by lazezo2** [comment]
Thanks
