### ISSUE TITLE
new update?

### ISSUE THREAD

**Issue by eluancardoso** [xtekky/TikTok-Shape-Sec#3]
in webbrowser normal can like, so using request not work digg =1, any about new update?

**Comment by xtekky** [comment]
the shape signing is not working really good, you may also start a fresh instance of the signer and unflagged accounts

**Comment by eluancardoso** [comment]
I'm not good at reverse engineering, but I'll try to understand how this works and maybe I can contribute something, anyway thanks a lot for sharing
